// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_ANDROID_API_KEY', // Ganti dengan API Key dari google-services.json
    appId: 'YOUR_ANDROID_APP_ID', // Ganti dengan mobilesdk_app_id dari google-services.json
    messagingSenderId: 'YOUR_SENDER_ID', // Ganti dengan project_number dari google-services.json
    projectId: 'inspire', // Nama project Firebase Anda
    storageBucket: 'inspire.firebasestorage.app', // Ganti jika berbeda
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY', // Ganti dengan API Key dari GoogleService-Info.plist
    appId: 'YOUR_IOS_APP_ID', // Ganti dengan GOOGLE_APP_ID dari GoogleService-Info.plist
    messagingSenderId: 'YOUR_SENDER_ID', // Ganti dengan GCM_SENDER_ID dari GoogleService-Info.plist
    projectId: 'inspire', // Nama project Firebase Anda
    storageBucket: 'inspire.firebasestorage.app', // Ganti jika berbeda
    iosBundleId: 'com.example.inspire', // Ganti dengan bundle ID iOS Anda
  );
}
