// Mocks generated by Mockito 5.4.6 from annotations
// in inspire/test/helpers/test_helpers.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:inspire/core/data_sources/data_sources.dart' as _i2;
import 'package:inspire/features/login/data/repositories/login_repository.dart'
    as _i3;
import 'package:inspire/features/login/domain/services/login_service.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAuthData_0 extends _i1.SmartFake implements _i2.AuthData {
  _FakeAuthData_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [LoginRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoginRepository extends _i1.Mock implements _i3.LoginRepository {
  MockLoginRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.AuthData> login({
    required String? identifier,
    required String? password,
    String? fcmToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#login, [], {
              #identifier: identifier,
              #password: password,
              #fcmToken: fcmToken,
            }),
            returnValue: _i4.Future<_i2.AuthData>.value(
              _FakeAuthData_0(
                this,
                Invocation.method(#login, [], {
                  #identifier: identifier,
                  #password: password,
                  #fcmToken: fcmToken,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.AuthData>);

  @override
  _i4.Future<_i2.AuthData> refreshToken({required String? refreshToken}) =>
      (super.noSuchMethod(
            Invocation.method(#refreshToken, [], {#refreshToken: refreshToken}),
            returnValue: _i4.Future<_i2.AuthData>.value(
              _FakeAuthData_0(
                this,
                Invocation.method(#refreshToken, [], {
                  #refreshToken: refreshToken,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.AuthData>);
}

/// A class which mocks [LoginService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoginService extends _i1.Mock implements _i5.LoginService {
  MockLoginService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> login({
    required String? identifier,
    required String? password,
    String? fcmToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#login, [], {
              #identifier: identifier,
              #password: password,
              #fcmToken: fcmToken,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> refreshToken() =>
      (super.noSuchMethod(
            Invocation.method(#refreshToken, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
